<section class="summary-notices">
    <p>
        <span class="emphase">Guaranteed position :</span> requires an additionnal 25%
    </p>
    <br />
    <p>
        <span class="emphase">Digital Vertical :</span> Purchase of all displays or by structure (2 sides)<br/>
        Increase of 25% for selective buying
    </p>
    <br />
    <p>
        The calculation of these impressions does not include the impressions that can be generated by specialty media
    </p>
    <br />
    <p>
        This proposal is valid for 30 days and does not guarantee the availabilities
    </p>
    <br />
    <p>
        <strong>Important note</strong>
        <span class="emphase">
        When a contract is requested, the inventory is booked for you until the next 48 hours. After this, Neo cannot guarantee the entirety of the requested inventory.
    </span>
    </p>
</section>
